/**
 * Edit-error diagnostics for the compact-tools edit wrapper.
 *
 * This module does NOT apply edits. It only inspects file text and the
 * attempted edits to produce actionable failure messages for 2026 LLMs.
 *
 * All matching here is for messaging only; the actual edit is still run by
 * Pi's native createEditTool. Outputs are bounded so long files cannot dump
 * tokens into an error response.
 */

export interface EditAttempt {
	oldText: string;
	newText: string;
}

const MAX_CANDIDATE_LINES = 20;
const MAX_MESSAGE_CHARS = 4000;
const MAX_OCCURRENCE_LINES = 10;

function normalizeNewlines(text: string): string {
	return text.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

function trimTrailingWs(line: string): string {
	return line.replace(/\s+$/, "");
}

/**
 * Strip leading indentation common to every non-empty line. Used to build
 * comparable shapes without changing the meaning of the attempted edit.
 */
function removeCommonIndent(text: string): string {
	const lines = text.split("\n");
	let minIndent = Number.POSITIVE_INFINITY;
	for (const line of lines) {
		if (line.trim().length === 0) continue;
		const leading = line.length - line.trimStart().length;
		if (leading < minIndent) minIndent = leading;
	}
	if (!Number.isFinite(minIndent) || minIndent <= 0) return text;
	return lines.map((line) => line.slice(minIndent)).join("\n");
}

function lineNumberOf(content: string, index: number): number {
	let line = 1;
	for (let i = 0; i < Math.min(index, content.length); i++) {
		if (content[i] === "\n") line++;
	}
	return line;
}

function truncateMessage(message: string): string {
	if (message.length <= MAX_MESSAGE_CHARS) return message;
	return `${message.slice(0, MAX_MESSAGE_CHARS)}\n... (diagnostic truncated)`;
}

function shortestHeadTailMatch(a: string, b: string): number {
	let i = 0;
	while (i < Math.min(a.length, b.length) && a[i] === b[i]) i++;
	let j = 0;
	while (
		j < Math.min(a.length, b.length) &&
		a[a.length - 1 - j] === b[b.length - 1 - j]
	) {
		j++;
	}
	return Math.max(i, j);
}

interface Candidate {
	index: number;
	line: number;
	score: number;
	contextLines: string[];
}

function findIndentTolerantCandidate(content: string, oldText: string): Candidate | null {
	const normalizedOld = removeCommonIndent(normalizeNewlines(oldText));
	const oldLines = normalizedOld.split("\n");
	// Remove a single trailing empty line generated by trailing newline if present.
	if (oldLines.length > 1 && oldLines[oldLines.length - 1] === "") oldLines.pop();
	if (oldLines.length === 0 || (oldLines.length === 1 && oldLines[0] === "")) return null;

	const contentLines = normalizeNewlines(content).split("\n");
	const candidates: Candidate[] = [];

	for (let i = 0; i < contentLines.length; i++) {
		if (!contentLines[i].trimStart().startsWith(oldLines[0].trimStart())) continue;

		// Heuristic: compare the candidate block against oldText with both common
		// indentation removed. Score by longest common prefix/suffix after
		// indentation normalization and trailing-whitespace collapse.
		const block = contentLines.slice(i, i + oldLines.length).join("\n");
		const normalizedBlock = removeCommonIndent(block);
		const score = shortestHeadTailMatch(
			normalizedBlock.replace(/\s+/g, " ").trim(),
			normalizedOld.replace(/\s+/g, " ").trim(),
		);

		const contextStart = Math.max(0, i - 2);
		const contextEnd = Math.min(contentLines.length, i + oldLines.length + 2);
		candidates.push({
			index: i,
			line: i + 1,
			score,
			contextLines: contentLines.slice(contextStart, contextEnd),
		});
	}

	candidates.sort((a, b) => b.score - a.score);
	if (candidates.length === 0 || candidates[0].score === 0) return null;
	// Only return a clear winner. If the top two are too close, do not guess.
	if (candidates.length > 1 && candidates[1].score >= candidates[0].score - 2) return null;
	return candidates[0];
}

function buildCandidateHint(candidate: Candidate, oldText: string): string {
	let hint = `Nearest similar block found around line ${candidate.line}:\n`;
	hint += "```\n";
	const targetIndent = removeCommonIndent(normalizeNewlines(oldText))
		.split("\n")
		.find((l) => l.trim().length > 0)?.length ?? 0;
	for (const line of candidate.contextLines.slice(0, MAX_CANDIDATE_LINES)) {
		const stripped = line.trimStart();
		const leading = line.length - stripped.length;
		const displayIndent = Math.max(0, leading - targetIndent);
		hint += `${" ".repeat(displayIndent)}${stripped}\n`;
	}
	hint += "```\n";
	hint += "Recommended action: re-read the file and copy the exact oldText from this block, including indentation.\n";
	return hint;
}

function listOccurrenceLines(content: string, oldText: string): number[] {
	const normalized = normalizeForSearch(content);
	const needle = normalizeForSearch(oldText);
	if (needle.length === 0) return [];
	const lines: number[] = [];
	let index = normalized.indexOf(needle, 0);
	while (index !== -1) {
		lines.push(lineNumberOf(content, index));
		index += Math.max(1, needle.length);
		index = normalized.indexOf(needle, index);
	}
	return [...new Set(lines)];
}

function normalizeForSearch(text: string): string {
	return normalizeNewlines(text)
		.split("\n")
		.map((line) => trimTrailingWs(line))
		.join("\n");
}

function describeOccurrences(content: string, oldText: string): string {
	const lines = listOccurrenceLines(content, oldText);
	if (lines.length === 0) return "";
	const shown = lines.slice(0, MAX_OCCURRENCE_LINES);
	let text = `Found ${lines.length} occurrence(s) at line(s): ${shown.join(", ")}`;
	if (lines.length > shown.length) text += ` (and ${lines.length - shown.length} more)`;
	text += ". Add surrounding context to make oldText unique.\n";
	return text;
}

function buildNoCandidateHint(): string {
	return (
		"No similar block found. Recommended action: re-read the file with " +
		"`read` to get the current content, then copy the exact oldText.\n"
	);
}

function buildNotFoundMessage(path: string, edit: EditAttempt, content: string): string {
	const candidate = findIndentTolerantCandidate(content, edit.oldText);
	let hint: string;
	if (candidate) {
		hint = buildCandidateHint(candidate, edit.oldText);
	} else {
		hint = buildNoCandidateHint();
	}
	const firstLine = `Could not find the exact text in ${path}. The oldText must match exactly, including all whitespace and newlines.`;
	return truncateMessage(`${firstLine}\n${hint}`);
}

function buildEmptyOldTextMessage(path: string): string {
	return `oldText must not be empty in ${path}. Provide the text you want to replace.`;
}

function buildNoChangeMessage(path: string): string {
	return `No changes made to ${path}. The replacements produced identical content. Verify oldText and newText differ.`;
}

function buildOverlapMessage(path: string, index1: number, index2: number): string {
	return (
		`edits[${index1}] and edits[${index2}] overlap in ${path}. ` +
		`Merge them into one edit or target disjoint regions.`
	);
}

function buildDuplicateMessage(
	path: string,
	content: string,
	edit: EditAttempt,
	editIndex: number,
	totalEdits: number,
): string {
	const base =
		totalEdits === 1
			? `Found multiple occurrences of the text in ${path}. The text must be unique.`
			: `Found multiple occurrences of edits[${editIndex}] in ${path}. Each oldText must be unique.`;
	const occurrences = describeOccurrences(content, edit.oldText);
	return truncateMessage(`${base}\n${occurrences}`);
}

function classifyEditError(error: Error): string {
	const message = error.message;
	if (message.includes("oldText must not be empty")) return "empty";
	if (message.includes("No changes made")) return "no-change";
	if (message.includes("overlap")) return "overlap";
	if (message.includes("occurrences") || message.includes("unique")) return "duplicate";
	if (message.includes("Could not find") || message.includes("oldText must match")) return "not-found";
	if (message.includes("Could not edit file")) return "io";
	return "unknown";
}

function editIndexFromMessage(message: string, totalEdits: number): number {
	const match = message.match(/edits\[(\d+)\]/);
	if (match) return Number.parseInt(match[1], 10);
	if (totalEdits === 1) return 0;
	return -1;
}

/**
 * Build an enriched edit error message. `content` is the current file text
 * (LF-normalized). `edits` are the attempted edits. `originalError` is the
 * Error thrown by the native edit tool. The returned string is meant to be
 * re-thrown as the tool result text; it never modifies the file.
 */
export function buildEditErrorMessage(
	path: string,
	content: string,
	edits: EditAttempt[],
	originalError: Error,
): string {
	const kind = classifyEditError(originalError);
	const totalEdits = edits.length;

	switch (kind) {
		case "empty":
			return buildEmptyOldTextMessage(path);
		case "no-change":
			return buildNoChangeMessage(path);
		case "overlap": {
			const match = originalError.message.match(/edits\[(\d+)\] and edits\[(\d+)\]/);
			if (match) {
				return buildOverlapMessage(
					path,
					Number.parseInt(match[1], 10),
					Number.parseInt(match[2], 10),
				);
			}
			return originalError.message;
		}
		case "duplicate": {
			const idx = editIndexFromMessage(originalError.message, totalEdits);
			const edit = edits[idx] ?? { oldText: "", newText: "" };
			return buildDuplicateMessage(path, content, edit, idx, totalEdits);
		}
		case "not-found": {
			const idx = editIndexFromMessage(originalError.message, totalEdits);
			const edit = edits[idx] ?? { oldText: "", newText: "" };
			return buildNotFoundMessage(path, edit, content);
		}
		case "io":
			return `${originalError.message}\nRecommended action: confirm the file exists and is writable, then retry.`;
		default:
			return `${originalError.message}\nRecommended action: re-read the file with \`read\` and verify oldText matches the current content exactly, including whitespace and newlines.`;
	}
}
